spring:
  application:
    name: othercode-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:salta_tech_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
logging:
  level:
    com.othercode: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    org.springframework.transaction: TRACE
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:jJ4Gs6z0vWZlJMQW6QzK6AzyvSvhk1C2H1Xt1b+bh9GqB0HnEwNfX1pWxW4W2PjN}
    access-token-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES:15}
    refresh-token-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:1}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
